"use client";

// Premium MeetingForm component
// Generated by ChatGPT

import { motion } from "framer-motion";
import { CalendarDays, Clock3, Loader2, MapPin, MessageCircle, ArrowRight } from "lucide-react";
import { MeetingFormData, meetingLocations } from "./MeetingData";

interface Props {
  formData: MeetingFormData;
  loading: boolean;
  onChange: (key: keyof MeetingFormData, value: string) => void;
  onSubmit: () => void;
}

export default function MeetingForm({
  formData,
  loading,
  onChange,
  onSubmit,
}: Props) {
  const today = new Date().toISOString().split("T")[0];
  const isDisabled = !formData.date || !formData.time || !formData.location;

  return (
    <motion.section
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: .7 }}
      className="flex min-h-screen items-center justify-center px-6 py-20"
    >
      <div className="relative w-full max-w-2xl overflow-hidden rounded-[40px] border border-white/10 bg-gradient-to-br from-white/10 via-white/5 to-white/10 p-10 shadow-[0_25px_80px_rgba(0,0,0,.45)] backdrop-blur-3xl md:p-14">

        <div className="absolute -left-32 -top-32 h-72 w-72 rounded-full bg-sky-500/10 blur-[100px]" />
        <div className="absolute -bottom-40 -right-32 h-80 w-80 rounded-full bg-blue-500/10 blur-[120px]" />

        <div className="text-center">
          <div className="inline-flex rounded-full border border-sky-400/20 bg-sky-500/10 px-5 py-2">
            <span className="text-xs uppercase tracking-[5px] text-sky-300">Final Chapter</span>
          </div>

          <h1 className="mt-8 text-5xl font-bold text-white">
            Let's Meet
          </h1>

          <p className="mx-auto mt-6 max-w-lg text-lg leading-9 text-blue-100">
            Every beautiful memory begins with one simple decision.
            <br />
            I hope our next one starts here.
          </p>
        </div>

        <div className="my-10 border-t border-white/10"></div>

        <div className="space-y-8">

          <div>
            <label className="mb-3 flex items-center gap-3 text-white">
              <CalendarDays size={18} className="text-sky-400" />
              Choose a Date
            </label>

            <input
              type="date"
              min={today}
              value={formData.date}
              onChange={(e)=>onChange("date",e.target.value)}
              className="w-full rounded-2xl border border-white/10 bg-slate-900/40 px-6 py-5 text-lg text-white outline-none transition-all focus:border-sky-400 focus:ring-4 focus:ring-sky-400/10"
            />
          </div>

          <div className="border-t border-white/10 pt-8">
            <label className="mb-3 flex items-center gap-3 text-white">
              <Clock3 size={18} className="text-sky-400" />
              Choose a Time
            </label>

            <input
              type="time"
              value={formData.time}
              onChange={(e)=>onChange("time",e.target.value)}
              className="w-full rounded-2xl border border-white/10 bg-slate-900/40 px-6 py-5 text-lg text-white outline-none transition-all focus:border-sky-400 focus:ring-4 focus:ring-sky-400/10"
            />
          </div>

          <div className="border-t border-white/10 pt-8">
            <label className="mb-3 flex items-center gap-3 text-white">
              <MapPin size={18} className="text-sky-400" />
              Choose a Place
            </label>

            <select
              value={formData.location}
              onChange={(e)=>onChange("location",e.target.value)}
              className="w-full rounded-2xl border border-white/10 bg-slate-900/40 px-6 py-5 text-lg text-white outline-none transition-all focus:border-sky-400 focus:ring-4 focus:ring-sky-400/10"
            >
              <option value="" className="text-black">Select Meeting Place</option>
              {meetingLocations.map((item)=>(
                <option key={item.id} value={item.name} className="text-black">
                  {item.name}
                </option>
              ))}
            </select>
          </div>

          <div className="border-t border-white/10 pt-8">
            <label className="mb-3 flex items-center gap-3 text-white">
              <MessageCircle size={18} className="text-sky-400" />
              Leave me a little message...
            </label>

            <textarea
              rows={5}
              value={formData.message}
              onChange={(e)=>onChange("message",e.target.value)}
              placeholder="Write something from your heart..."
              className="w-full resize-none rounded-2xl border border-white/10 bg-slate-900/40 px-6 py-5 text-lg text-white placeholder:text-blue-200 outline-none transition-all focus:border-sky-400 focus:ring-4 focus:ring-sky-400/10"
            />
          </div>

          <motion.button
            whileHover={{ scale: isDisabled || loading ? 1 : 1.02 }}
            whileTap={{ scale: isDisabled || loading ? 1 : .98 }}
            disabled={isDisabled || loading}
            onClick={onSubmit}
            className={`group relative flex w-full items-center justify-center overflow-hidden rounded-2xl py-5 text-lg font-semibold transition-all ${
              isDisabled || loading
                ? "cursor-not-allowed bg-gray-600 text-white"
                : "bg-gradient-to-r from-sky-500 via-blue-600 to-indigo-700 text-white shadow-[0_15px_40px_rgba(37,99,235,.45)]"
            }`}
          >
            <span className="relative z-10 flex items-center gap-3">
              {loading ? (
                <>
                  <Loader2 className="animate-spin" size={20} />
                  Sending...
                </>
              ) : (
                <>
                  Let's Meet Together
                  <ArrowRight className="transition-transform group-hover:translate-x-1" size={18}/>
                </>
              )}
            </span>
          </motion.button>
        </div>

      </div>
    </motion.section>
  );
}
